### ISSUE TITLE
Lack of code comments

### ISSUE THREAD

**Issue by ghost** [SRAZKVT/KuteForth#3]
Yes I'm making an issue about this.  
The compiler file has very few comments (and a lot of them are something like "this doesn't work yet"). This is a large problem for both code readability and future maintainability, and should really be resolved before it becomes a large issue.

**Comment by SRAZKVT** [comment]
That is indeed an issue as of now, most of the compiler will be completely redone whenever going selfhosted, but it is true that comments explaining current behaviour would do no harm.
